<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(AmanhecerTargetFrameworks)</TargetFrameworks>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Amanhecer\Amanhecer.csproj" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0' OR '$(TargetFramework)' == 'net462'">
        <PackageReference Include="System.Threading.Channels" />
    </ItemGroup>

</Project>
