<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <TargetFramework>net10.0</TargetFramework>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.Logging" />
        <PackageReference Include="TUnit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Amanhecer.Abstractions\Amanhecer.Abstractions.csproj" />
        <ProjectReference Include="..\..\src\Amanhecer\Amanhecer.csproj" />
        <ProjectReference Include="..\..\src\Amanhecer.InMemory\Amanhecer.InMemory.csproj" />
        <ProjectReference Include="..\..\src\Amanhecer.Compression.LZ4\Amanhecer.Compression.LZ4.csproj" />
        <ProjectReference Include="..\..\src\Amanhecer.Compression.Snappier\Amanhecer.Compression.Snappier.csproj" />
        <ProjectReference Include="..\..\src\Amanhecer.Compression.Zstd\Amanhecer.Compression.Zstd.csproj" />
    </ItemGroup>
</Project>
