<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <TargetFramework>net10.0</TargetFramework>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="RabbitMQ.Client" />
        <PackageReference Include="TUnit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Amanhecer.RabbitMq\Amanhecer.RabbitMq.csproj" />
        <ProjectReference Include="..\Amanhecer.Messaging.Base.Tests\Amanhecer.Messaging.Base.Tests.csproj" />
    </ItemGroup>

</Project>
