<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(AmanhecerCoreTargetFrameworks)</TargetFrameworks>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Dekaf" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Amanhecer\Amanhecer.csproj" />
    </ItemGroup>

</Project>
